### ISSUE TITLE
ReferenceError: Cannot access 'reactStarted' before initialization

### ISSUE THREAD

**Issue by yelkarama** [ironboy/react-amazing-proxy#1]
Followed the setup steps but I get the following error when trying to start the app:

ReferenceError: Cannot access 'reactStarted' before initialization
    at startReact (/home/younes/my-app/node_modules/react-amazing-proxy/start.js:195:3)
    at Object.<anonymous> (/home/younes/my-app/node_modules/react-amazing-proxy/start.js:189:3)
    at Module._compile (internal/modules/cjs/loader.js:1139:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1159:10)
    at Module.load (internal/modules/cjs/loader.js:988:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-app@0.1.0 start: `node node_modules/react-amazing-proxy/start "dev"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the my-app@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/younes/.npm/_logs/2020-02-03T07_11_19_714Z-debug.log

**Comment by ironboy** [comment]
This should be fixed in version 1.0.63:

https://github.com/ironboy/react-amazing-proxy/commit/6aaf43e54bcf0863b0351aa6f080520990f61eb7
